/*
 * This file was automatically generated by EvoSuite
 * Thu Jan 04 11:09:36 GMT 2018
 */

package com.polimi.fakePTS;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.polimi.fakePTS.RandomTicketId;
import java.util.Random;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.TooManyResourcesException;
import org.evosuite.runtime.mock.java.util.MockRandom;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class RandomTicketId_ESTest extends RandomTicketId_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      RandomTicketId randomTicketId0 = new RandomTicketId(3644);
      randomTicketId0.nextString();
      randomTicketId0.nextString();
      // Undeclared exception!
      try { 
        randomTicketId0.nextString();
        fail("Expecting exception: TooManyResourcesException");
      
      } catch(TooManyResourcesException e) {
         //
         // Loop has been executed more times than the allowed 10000
         //
         assertThrownBy("org.evosuite.runtime.LoopCounter", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      RandomTicketId randomTicketId0 = null;
      try {
        randomTicketId0 = new RandomTicketId(1, (Random) null, "xduP");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("java.util.Objects", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      RandomTicketId randomTicketId0 = null;
      try {
        randomTicketId0 = new RandomTicketId(1926, (Random) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("java.util.Objects", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      RandomTicketId randomTicketId0 = null;
      try {
        randomTicketId0 = new RandomTicketId(0, (Random) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("com.polimi.fakePTS.RandomTicketId", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      MockRandom mockRandom0 = new MockRandom();
      RandomTicketId randomTicketId0 = new RandomTicketId(2, (Random) mockRandom0, "AA");
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      MockRandom mockRandom0 = new MockRandom();
      RandomTicketId randomTicketId0 = null;
      try {
        randomTicketId0 = new RandomTicketId(0, (Random) mockRandom0, "-A);kH");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("com.polimi.fakePTS.RandomTicketId", e);
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      MockRandom mockRandom0 = new MockRandom();
      RandomTicketId randomTicketId0 = new RandomTicketId(2, (Random) mockRandom0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      MockRandom mockRandom0 = new MockRandom();
      RandomTicketId randomTicketId0 = null;
      try {
        randomTicketId0 = new RandomTicketId(1227, (Random) mockRandom0, "");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("com.polimi.fakePTS.RandomTicketId", e);
      }
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      RandomTicketId randomTicketId0 = null;
      try {
        randomTicketId0 = new RandomTicketId(0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("com.polimi.fakePTS.RandomTicketId", e);
      }
  }
}
